# Q1: Import numpy library

In [2]:
import numpy as np

# Q2: Generate a sequence of 15 floats using linspace() function

In [3]:
np.linspace(0,20,15)

array([ 0.        ,  1.42857143,  2.85714286,  4.28571429,  5.71428571,
        7.14285714,  8.57142857, 10.        , 11.42857143, 12.85714286,
       14.28571429, 15.71428571, 17.14285714, 18.57142857, 20.        ])

# Q3: Create a 3-D array in shape (2, 2, 3) containing the four arrays given below 
Note : the array's name is up to you.

|      |       |          |         |
|------| ----- | -------- | ------- |
|arr1 | 1.1    | 2.1       | 3.1        |
|arr2 | 4.1    | 5.1       | 6.1        |
|arr3 | 7.1    | 8.1       | 9.1        |
|arr4 | 10.1   | 11.1      | 12.1       |

In [5]:
x = np.array(
    [
        [
            [1.1, 2.1, 3.1],
            [4.1, 5.1, 6.1],
            
        ],
        [
            [7.1, 8.1, 9.1],
            [10.1, 11.1, 12.1],
            
        ]
    ])
x.shape

(2, 2, 3)

# Q4: Print the following:
Note: use the same array from Q3.
- Array's type.
- Array's elements datatype.
- Array's shape.
- Array's size.
- Array's dimention.

In [8]:
print(type(x))
print(x.dtype)
print(x.shape)
print(x.size)
print(x.ndim)



<class 'numpy.ndarray'>
float64
(2, 2, 3)
12
3


# Q5:  Change the array dimention from 3-D to 4-D
Note: use the same array from Q3.
- Create a new array to hold the changes. 
- Print the new array's dimention and shape.

In [17]:
new_shape = (1, x.shape[0], x.shape[1], x.shape[2])
x_4d = np.reshape(x, new_shape)


print(x_4d.shape)
print(x_4d.ndim)


(1, 2, 2, 3)
4


# Q6: Change the array's elements datatype to integer  
Note: use the same array from Q5.

- Create a new array to hold the changes. 
- Print the new array.

In [18]:
x_int = x.astype(int)
print (x_int)

[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]


# Q7: Print all array's elements using for loop
Note: use the same array from Q6.

Hint: use nditer()

In [21]:
for y in np.nditer(x_int):
    print(y)

1
2
3
4
5
6
7
8
9
10
11
12


# Q8:  Print number 8 using array slicing
Note: use the same array from Q6.

In [23]:
x_int[1][0][1]

8

# Q9: Print number 5 and number 6 using array slicing
Note: use the same array from Q6.

In [25]:
print(x_int[0][1][1])
print(x_int[0][1][2])

5
6


# Q10: Search for number 8 using where()
Note: use the same array from Q6.

Note: where() is only used with small data.

*the output represents the path of the index that leads to number 8*

In [27]:
ind = np.where(x == 8)

print(ind)

(array([], dtype=int64), array([], dtype=int64), array([], dtype=int64))


# Q11: Reshape the array as the following

    array([[[ 1, 2],
            [ 3,  4],
            [ 5,  6]],

           [[ 7,  8],
            [ 9, 10],
            [11, 12]]])
            
 Note: use the same array from Q6.

In [30]:
new_shape = (2, 3, 2)
x_reshaped = np.reshape(x_int, new_shape)
x_reshaped

array([[[ 1,  2],
        [ 3,  4],
        [ 5,  6]],

       [[ 7,  8],
        [ 9, 10],
        [11, 12]]])

# Q12: Join the given arrays below 
    arr1 = np.array([['A', 'B'], ['E', 'F']])
    arr2 = np.array([['C', 'D'], ['G', 'H']])
## Q12.1: Join the arrays without specifying the axis 

### Q12.1: using concatenate() function

In [37]:
x = np.concatenate((arr1, arr2))
x

array([['A', 'B'],
       ['E', 'F'],
       ['C', 'D'],
       ['G', 'H']], dtype='<U1')

### Q12.1: Join the arrays with vstack() function

In [38]:
arr1 = np.array([['A', 'B'], 
                 ['E', 'F']])

arr2 = np.array([['C', 'D'], 
                 ['G', 'H']])


result = np.vstack((arr1, arr2))
result

array([['A', 'B'],
       ['E', 'F'],
       ['C', 'D'],
       ['G', 'H']], dtype='<U1')

# Q12.2: Join the arrays along rows with axis = 1 

### Q12.2: using concatenate() function

In [40]:
y = np.concatenate((arr1, arr2), axis=1)
y

array([['A', 'B', 'C', 'D'],
       ['E', 'F', 'G', 'H']], dtype='<U1')

### Q12.1: Join the arrays with hstack() function

In [39]:
resul = np.hstack((arr1, arr2))
resul

array([['A', 'B', 'C', 'D'],
       ['E', 'F', 'G', 'H']], dtype='<U1')

# Q13: Split the array into two arrays with axis = 1, each array should contain four arrays. 
Note: use the same array from Q12.1

In [43]:
spl = np.split(x, 2, axis=1)
spl

[array([['A'],
        ['E'],
        ['C'],
        ['G']], dtype='<U1'),
 array([['B'],
        ['F'],
        ['D'],
        ['H']], dtype='<U1')]