# Q1: Import numpy library

In [1]:
import numpy as np

# Q2: Generate a sequence of 15 floats using linspace() function

In [2]:
a = np.linspace(0,20,15)
a

array([ 0.        ,  1.42857143,  2.85714286,  4.28571429,  5.71428571,
        7.14285714,  8.57142857, 10.        , 11.42857143, 12.85714286,
       14.28571429, 15.71428571, 17.14285714, 18.57142857, 20.        ])

# Q3: Create a 3-D array in shape (2, 2, 3) containing the four arrays given below 
Note : the array's name is up to you.

|      |       |          |         |
|------| ----- | -------- | ------- |
|arr1 | 1.1    | 2.1       | 3.1        |
|arr2 | 4.1    | 5.1       | 6.1        |
|arr3 | 7.1    | 8.1       | 9.1        |
|arr4 | 10.1   | 11.1      | 12.1       |

In [3]:
array3D = np.array([[[1.1, 2.1, 3.1],[4.1, 5.1, 6.1]],
           [[7.1, 8.1, 9.1],[10.1, 11.1, 12.1]]])
array3D

array([[[ 1.1,  2.1,  3.1],
        [ 4.1,  5.1,  6.1]],

       [[ 7.1,  8.1,  9.1],
        [10.1, 11.1, 12.1]]])

# Q4: Print the following:
Note: use the same array from Q3.
- Array's type.
- Array's elements datatype.
- Array's shape.
- Array's size.
- Array's dimention.

In [4]:
print('Array type: ',type(array3D), '\nArray elements datatype: ', array3D.dtype,'\nArray shape: ', array3D.shape
      ,'\nArray size: ', array3D.size ,'\nArray dimention: ', array3D.ndim)

Array type:  <class 'numpy.ndarray'> 
Array elements datatype:  float64 
Array shape:  (2, 2, 3) 
Array size:  12 
Array dimention:  3


# Q5:  Change the array dimention from 3-D to 4-D
Note: use the same array from Q3.
- Create a new array to hold the changes. 
- Print the new array's dimention and shape.

In [5]:
newArray = np.reshape(array3D,(2,2,1,3))
print('array shape ',newArray.shape,'\narray dimention ',newArray.ndim)

array shape  (2, 2, 1, 3) 
array dimention  4


# Q6: Change the array's elements datatype to integer  
Note: use the same array from Q5.

- Create a new array to hold the changes. 
- Print the new array.

In [6]:
newArray2 = newArray.astype(int)
newArray2.dtype

dtype('int64')

# Q7: Print all array's elements using for loop
Note: use the same array from Q6.

Hint: use nditer()

In [7]:
for i in np.nditer(newArray2):
               print(i)

1
2
3
4
5
6
7
8
9
10
11
12


# Q8:  Print number 8 using array slicing
Note: use the same array from Q6.

In [8]:
newArray2[1,0,0,1]
newArray2[:,:,:,:] 

array([[[[ 1,  2,  3]],

        [[ 4,  5,  6]]],


       [[[ 7,  8,  9]],

        [[10, 11, 12]]]])

# Q9: Print number 5 and number 6 using array slicing
Note: use the same array from Q6.

In [9]:
print(newArray2[0,1,0,1],newArray2[0,1,0,2])

5 6


# Q10: Search for number 8 using where()
Note: use the same array from Q6.

Note: where() is only used with small data.

*the output represents the path of the index that leads to number 8*

In [10]:
np.where(newArray2 == 8)

(array([1]), array([0]), array([0]), array([1]))

# Q11: Reshape the array as the following

    array([[[ 1, 2],
            [ 3,  4],
            [ 5,  6]],

           [[ 7,  8],
            [ 9, 10],
            [11, 12]]])
            
 Note: use the same array from Q6.

In [11]:
np.reshape(newArray2,(2,3,2))

array([[[ 1,  2],
        [ 3,  4],
        [ 5,  6]],

       [[ 7,  8],
        [ 9, 10],
        [11, 12]]])

# Q12: Join the given arrays below 
    arr1 = np.array([['A', 'B'], ['E', 'F']])
    arr2 = np.array([['C', 'D'], ['G', 'H']])
## Q12.1: Join the arrays without specifying the axis 

In [12]:
arr1 = np.array([['A', 'B'], ['E', 'F']])
arr2 = np.array([['C', 'D'], ['G', 'H']])
newArray3= np.concatenate((arr1,arr2))
newArray3

array([['A', 'B'],
       ['E', 'F'],
       ['C', 'D'],
       ['G', 'H']], dtype='<U1')

# Q12.2: Join the arrays along rows with axis = 1 

In [13]:
np.concatenate((arr1,arr2), axis=1)

array([['A', 'B', 'C', 'D'],
       ['E', 'F', 'G', 'H']], dtype='<U1')

# Q13: Split the array into two arrays with axis = 1, each array should contain four arrays. 
Note: use the same array from Q12.1

In [14]:
np.split(newArray3,2,axis=1)

[array([['A'],
        ['E'],
        ['C'],
        ['G']], dtype='<U1'),
 array([['B'],
        ['F'],
        ['D'],
        ['H']], dtype='<U1')]