# Q1: Import numpy library

In [1]:
# write your code here ^_^
import numpy as np

    

# Q2: Generate a sequence of 15 floats using linspace() function

In [2]:
# write your code here ^_^
np.linspace(0,15,num=15,dtype=float)

array([ 0.        ,  1.07142857,  2.14285714,  3.21428571,  4.28571429,
        5.35714286,  6.42857143,  7.5       ,  8.57142857,  9.64285714,
       10.71428571, 11.78571429, 12.85714286, 13.92857143, 15.        ])

# Q3: Create a 3-D array in shape (2, 2, 3) containing the four arrays given below 
Note : the array's name is up to you.

|      |       |          |         |
|------| ----- | -------- | ------- |
|arr1 | 1.1    | 2.1       | 3.1        |
|arr2 | 4.1    | 5.1       | 6.1        |
|arr3 | 7.1    | 8.1       | 9.1        |
|arr4 | 10.1   | 11.1      | 12.1       |

In [3]:
# write your code here ^_^
array_3D = [
    [1.1,2.1,3.1],
    [4.1,5.1,6.1],
    [7.1,8.1,9.1],
    [10.1,11.1,12.1]
] 
array_3D = np.array(array_3D) #convert list into array
array_3D = array_3D.reshape(2,2,3) #define array shape


# Q4: Print the following:
Note: use the same array from Q3.
- Array's type.
- Array's elements datatype.
- Array's shape.
- Array's size.
- Array's dimention.

In [4]:
# write your code here ^_^
print("Array's type : ", type(array_3D))
print("Array's elements datatype", array_3D.dtype)
print("Array's shape :", array_3D.shape)
print("Array's size :", array_3D.size)
print("Array's dimension: ",array_3D.ndim)

Array's type :  <class 'numpy.ndarray'>
Array's elements datatype float64
Array's shape : (2, 2, 3)
Array's size : 12
Array's dimension:  3


# Q5:  Change the array dimention from 3-D to 4-D
Note: use the same array from Q3.
- Create a new array to hold the changes. 
- Print the new array's dimention and shape.

In [5]:
# write your code here ^_^
array_4D = array_3D.reshape(1,2,2,3)
print("Array's Dimension :",array_4D.ndim)
print("Arra's Shape : ",array_4D.shape)


Array's Dimension : 4
Arra's Shape :  (1, 2, 2, 3)


# Q6: Change the array's elements datatype to integer  
Note: use the same array from Q5.

- Create a new array to hold the changes. 
- Print the new array.

In [6]:
# write your code here ^_^
new_array_int = array_4D.copy()
new_array_int = new_array_int.astype(int)
#The reason for using three loops is to get rid of extra brackets
for array in new_array_int:
    for row in array:
        for item in row:
            print(item)

  

[1 2 3]
[4 5 6]
[7 8 9]
[10 11 12]


## Q7: Print all array's elements using for loop
Note: use the same array from Q6.

Hint: use nditer()

In [7]:
# write your code here ^_^
with np.nditer(new_array_int) as array:
    for item in array:
        print(item)
    

1
2
3
4
5
6
7
8
9
10
11
12


# Q8:  Print number 8 using array slicing
Note: use the same array from Q6.

In [8]:
# write your code here ^_^
new_array_int[::,1:2,0:1,1:2] #[dimension, array, row, column]

array([[[[8]]]])

# Q9: Print number 5 and number 6 using array slicing
Note: use the same array from Q6.

In [16]:
# write your code here ^_^
new_array_int[::,0:1,1:3,1:3] #[dimension, array, row, column]

array([[[[5, 6]]]])

# Q10: Search for number 8 using where()
Note: use the same array from Q6.

Note: where() is only used with small data.

*the output represents the path of the index that leads to number 8*

In [10]:
# write your code here ^_^

print(np.where(new_array_int == 8),"\n")
print('\n To check the provided path is correct : \n')
print(new_array_int[0][1][0][1])

(array([0], dtype=int64), array([1], dtype=int64), array([0], dtype=int64), array([1], dtype=int64)) 


 To check the provided path is correct : 

8


# Q11: Reshape the array as the following

    array([[[ 1, 2],
            [ 3,  4],
            [ 5,  6]],

           [[ 7,  8],
            [ 9, 10],
            [11, 12]]])
            
 Note: use the same array from Q6.

In [11]:
# write your code here ^_^
print("Previous shape :\n",new_array_int,'\n')
print("new reshaped array :\n\n",new_array_int.reshape(2,3,2)) #(two arrays, 3 rows for each array, 2 columns)

Previous shape :
 [[[[ 1  2  3]
   [ 4  5  6]]

  [[ 7  8  9]
   [10 11 12]]]] 

new reshaped array :

 [[[ 1  2]
  [ 3  4]
  [ 5  6]]

 [[ 7  8]
  [ 9 10]
  [11 12]]]


# Q12: Join the given arrays below 
    arr1 = np.array([['A', 'B'], ['E', 'F']])
    arr2 = np.array([['C', 'D'], ['G', 'H']])
## Q12.1: Join the arrays without specifying the axis 

In [12]:
# write your code here ^_^
arr1 = np.array([['A', 'B'], ['E', 'F']])
arr2 = np.array([['C', 'D'], ['G', 'H']])
arr3 = np.concatenate((arr1,arr2))

print(arr3)


[['A' 'B']
 ['E' 'F']
 ['C' 'D']
 ['G' 'H']]


# Q12.2: Join the arrays along rows with axis = 1 

In [13]:
# write your code here ^_^
# np.concatenate((arr1,arr2),axis=1) can be used
arr4 = np.hstack((arr1,arr2)) #hstack has a default axis which equals to 1
print(arr4)
    

[['A' 'B' 'C' 'D']
 ['E' 'F' 'G' 'H']]


# Q13: Split the array into two arrays with axis = 1, each array should contain four arrays. 
Note: use the same array from Q12.1

In [14]:
# write your code here ^_^
arr_one,arr_two = np.split(arr3,2,axis=1) 
#each array contains 4 arrays
print('Array before split\n\n',arr3,'\n')
print('first array :\n',arr_one)
print('second array :\n',arr_two)

Array before split

 [['A' 'B']
 ['E' 'F']
 ['C' 'D']
 ['G' 'H']] 

first array :
 [['A']
 ['E']
 ['C']
 ['G']]
second array :
 [['B']
 ['F']
 ['D']
 ['H']]
