# Q1: Import numpy library

In [1]:
import numpy as np

# Q2: Generate a sequence of 15 floats using linspace() function

In [27]:
np.linspace(0 ,4,15)

array([0.        , 0.28571429, 0.57142857, 0.85714286, 1.14285714,
       1.42857143, 1.71428571, 2.        , 2.28571429, 2.57142857,
       2.85714286, 3.14285714, 3.42857143, 3.71428571, 4.        ])

# Q3: Create a 3-D array in shape (2, 2, 3) containing the four arrays given below 
Note : the array's name is up to you.

|      |       |          |         |
|------| ----- | -------- | ------- |
|arr1 | 1.1    | 2.1       | 3.1        |
|arr2 | 4.1    | 5.1       | 6.1        |
|arr3 | 7.1    | 8.1       | 9.1        |
|arr4 | 10.1   | 11.1      | 12.1       |

In [28]:
a= np.array([
    [
        [1.1, 2.1, 3.1],
        [4.1, 5.1, 6.1],
        [7.1, 8.1, 9.1],
        [10.1, 11.1, 12.1]
    ]
])

a

array([[[ 1.1,  2.1,  3.1],
        [ 4.1,  5.1,  6.1],
        [ 7.1,  8.1,  9.1],
        [10.1, 11.1, 12.1]]])

# Q4: Print the following:
Note: use the same array from Q3.
- Array's type.
- Array's elements datatype.
- Array's shape.
- Array's size.
- Array's dimention.

In [30]:
z=type(a)
zz=a.dtype 
zzz=a.shape
zzzz=a.size 
zzzzz=a.ndim
print(z,"\n",zz,"\n",zzz,"\n",zzzz,"\n",zzzzz,"\n")

<class 'numpy.ndarray'> 
 float64 
 (1, 4, 3) 
 12 
 3 



# Q5:  Change the array dimention from 3-D to 4-D
Note: use the same array from Q3.
- Create a new array to hold the changes. 
- Print the new array's dimention and shape.

In [31]:
x = a.reshape(2,2,1,3)
print(x.shape)
x

(2, 2, 1, 3)


array([[[[ 1.1,  2.1,  3.1]],

        [[ 4.1,  5.1,  6.1]]],


       [[[ 7.1,  8.1,  9.1]],

        [[10.1, 11.1, 12.1]]]])

# Q6: Change the array's elements datatype to integer  
Note: use the same array from Q5.

- Create a new array to hold the changes. 
- Print the new array.

In [37]:
v = x.astype(int)
v

array([[[[ 1,  2,  3]],

        [[ 4,  5,  6]]],


       [[[ 7,  8,  9]],

        [[10, 11, 12]]]])

# Q7: Print all array's elements using for loop
Note: use the same array from Q6.

Hint: use nditer()

In [38]:
for i in np.nditer(v):
    print(i)

1
2
3
4
5
6
7
8
9
10
11
12


# Q8:  Print number 8 using array slicing
Note: use the same array from Q6.

In [44]:
v[1,[0],[0],[1]]


array([8])

# Q9: Print number 5 and number 6 using array slicing
Note: use the same array from Q6.

In [50]:
v[0,1,0,1:]


array([5, 6])

# Q10: Search for number 8 using where()
Note: use the same array from Q6.

Note: where() is only used with small data.

*the output represents the path of the index that leads to number 8*

In [51]:
np.where(v == 8)

(array([1], dtype=int64),
 array([0], dtype=int64),
 array([0], dtype=int64),
 array([1], dtype=int64))

# Q11: Reshape the array as the following

    array([[[ 1, 2],
            [ 3,  4],
            [ 5,  6]],

           [[ 7,  8],
            [ 9, 10],
            [11, 12]]])
            
 Note: use the same array from Q6.

In [52]:
v.reshape(2,3,2)

array([[[ 1,  2],
        [ 3,  4],
        [ 5,  6]],

       [[ 7,  8],
        [ 9, 10],
        [11, 12]]])

# Q12: Join the given arrays below 
    arr1 = np.array([['A', 'B'], ['E', 'F']])
    arr2 = np.array([['C', 'D'], ['G', 'H']])
## Q12.1: Join the arrays without specifying the axis 

In [53]:
arr1 = np.array([['A', 'B'], ['E', 'F']])
arr2 = np.array([['C', 'D'], ['G', 'H']])
a3 = np.concatenate((arr1, arr2))
print(a3)

[['A' 'B']
 ['E' 'F']
 ['C' 'D']
 ['G' 'H']]


# Q12.2: Join the arrays along rows with axis = 1 

In [56]:
d= np.concatenate((arr1, arr2), axis=1)
d

array([['A', 'B', 'C', 'D'],
       ['E', 'F', 'G', 'H']], dtype='<U1')

# Q13: Split the array into two arrays with axis = 1, each array should contain four arrays. 
Note: use the same array from Q12.1

In [59]:
sp= np.split(a3, 2, axis=1)
sp

[array([['A'],
        ['E'],
        ['C'],
        ['G']], dtype='<U1'),
 array([['B'],
        ['F'],
        ['D'],
        ['H']], dtype='<U1')]